---
all:
  children:
    centos:
      children:
        splunk:
          hosts:
            beda-spl-sh01.mybeda.com:
        docker:
          hosts:
            unifi.mybeda.com:
        pihole:
          hosts:
            dns.mybeda.com:
        wazuh:
          hosts:
            wazuh1:
              ansible_host: 10.1.12.53
        xsoar:
          hosts:
            xsoar1:
              ansible_host: 10.1.12.63
        syslog:
          hosts:
            syslogng.mybeda.com:
        sc4s:
          hosts:
            sc4s.mybeda.com:
    debian:
      children:
        suricata:
          hosts:
            beda-pids-1.mybeda.com:
              ansible_user: pi

