---
- name: Add the SSH directory
  file:
    path: ~/.ssh
    state: directory
    mode: '0700'

- name: Add SSH authorized keys.
  copy:
    src: authorized_keys
    dest: ~/.ssh/authorized_keys
    mode: '0600'

- name: Setup no password sudo
  copy:
    src: no_pass
    dest: /etc/sudoers.d/
  become: yes