---
# roles/service/tasks/install.yml
- name: Yum add service {{ packages }}
  yum:
    name: '{{ packages }}'
    state: latest
  become: yes
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Apt add service {{ packages }}
  apt:
    name: '{{ packages }}'
    state: latest
  become: yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'