---
# defaults file for splunk_reload
splunk_url: 'https://localhost:8089/servicesNS/-/-'
splunk_admin_user: 'admin'
splunk_admin_password: 'Changeme'

splunk_reload_endpoints:
  - 'admin/conf-times'
  - 'data/ui/manager'
  - 'data/ui/nav'
  - 'data/ui/views'
  - 'admin/alert_actions'
  - 'admin/clusterconfig'
  - 'admin/commandsconf'
  - 'admin/conf-checklist'
  - 'admin/conf-deploymentclient'
  - 'admin/conf-inputs'
  - 'admin/conf-times'
  - 'admin/conf-wmi'
  - 'admin/crl'
  - 'admin/datamodel-files'
  - 'admin/datamodelacceleration'
  - 'admin/datamodeledit'
  - 'admin/dataset_consolidation_datamodeledit'
  - 'admin/deploymentserver'
  - 'admin/distsearch-peer'
  - 'admin/eventtypes'
  - 'admin/fields'
  - 'admin/fifo'
  - 'admin/fvtags'
  - 'admin/http'
  - 'admin/indexer-discovery-config'
  - 'admin/indexes'
  - 'admin/limits'
  - 'admin/livetail'
  - 'admin/localapps'
  - 'admin/macros'
  - 'admin/manager'
  - 'admin/messages-conf'
  - 'admin/modalerts'
  - 'admin/monitor'
  - 'admin/nav'
  - 'admin/panels'
  - 'admin/passwords'
  - 'admin/pools'
  - 'admin/proxysettings'
  - 'admin/raw'
  - 'admin/remote_eventlogs'
  - 'admin/remote_monitor'
  - 'admin/remote_perfmon'
  - 'admin/remote_raw'
  - 'admin/remote_script'
  - 'admin/remote_udp'
  - 'admin/savedsearch'
  - 'admin/scheduledviews'
  - 'admin/script'
  - 'admin/serverclasses'
  - 'admin/shclusterconfig'
  - 'admin/sourcetypes'
  - 'admin/ssl'
  - 'admin/syslog'
  - 'admin/tcpout-default'
  - 'admin/tcpout-group'
  - 'admin/tcpout-server'
  - 'admin/telemetry'
  - 'admin/transforms-extract'
  - 'admin/transforms-reload'
  - 'admin/udp'
  - 'admin/ui-prefs'
  - 'admin/ui-tour'
  - 'admin/views'
  - 'admin/viewstates'
  - 'admin/vix-indexes'
  - 'admin/vix-providers'
  - 'admin/workflow-actions'